platform:ios,'8.0'

target 'SwiftProject' do
use_frameworks!
pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire', '~> 4.6.0'
pod 'SwiftyJSON', '~> 4.0.0'
pod 'IQKeyboardManagerSwift', '~> 5.0.7'
pod 'SwiftFCXRefresh'
pod 'GTMRefresh'
pod 'Chrysan'
end
